/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as DocsImport } from './routes/docs'
import { Route as IndexImport } from './routes/index'
import { Route as DocsIndexImport } from './routes/docs/index'
import { Route as DocsShellPipesAndRedirectionImport } from './routes/docs/shell/pipes-and-redirection'
import { Route as DocsShellOverviewImport } from './routes/docs/shell/overview'
import { Route as DocsShellCustomizationImport } from './routes/docs/shell/customization'
import { Route as DocsShellCompletionAndEditingImport } from './routes/docs/shell/completion-and-editing'
import { Route as DocsShellCommandsImport } from './routes/docs/shell/commands'
import { Route as DocsShellActivityMonitorImport } from './routes/docs/shell/activity-monitor'
import { Route as DocsLanguageVectorsImport } from './routes/docs/language/vectors'
import { Route as DocsLanguageStringsImport } from './routes/docs/language/strings'
import { Route as DocsLanguagePatternMatchingImport } from './routes/docs/language/pattern-matching'
import { Route as DocsLanguageObjectOrientedImport } from './routes/docs/language/object-oriented'
import { Route as DocsLanguageNumbersImport } from './routes/docs/language/numbers'
import { Route as DocsLanguageGettingStartedImport } from './routes/docs/language/getting-started'
import { Route as DocsLanguageFunctionsImport } from './routes/docs/language/functions'
import { Route as DocsLanguageDatesImport } from './routes/docs/language/dates'
import { Route as DocsLanguageDataTypesImport } from './routes/docs/language/data-types'
import { Route as DocsLanguageControlFlowImport } from './routes/docs/language/control-flow'
import { Route as DocsLanguageBasicSyntaxImport } from './routes/docs/language/basic-syntax'
import { Route as DocsLanguageRouteComponentImport } from './routes/docs/language/RouteComponent'
import { Route as DocsGettingStartedInstallationImport } from './routes/docs/getting-started/installation'

// Create/Update Routes

const DocsRoute = DocsImport.update({
  id: '/docs',
  path: '/docs',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const DocsIndexRoute = DocsIndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DocsRoute,
} as any)

const DocsShellPipesAndRedirectionRoute =
  DocsShellPipesAndRedirectionImport.update({
    id: '/shell/pipes-and-redirection',
    path: '/shell/pipes-and-redirection',
    getParentRoute: () => DocsRoute,
  } as any)

const DocsShellOverviewRoute = DocsShellOverviewImport.update({
  id: '/shell/overview',
  path: '/shell/overview',
  getParentRoute: () => DocsRoute,
} as any)

const DocsShellCustomizationRoute = DocsShellCustomizationImport.update({
  id: '/shell/customization',
  path: '/shell/customization',
  getParentRoute: () => DocsRoute,
} as any)

const DocsShellCompletionAndEditingRoute =
  DocsShellCompletionAndEditingImport.update({
    id: '/shell/completion-and-editing',
    path: '/shell/completion-and-editing',
    getParentRoute: () => DocsRoute,
  } as any)

const DocsShellCommandsRoute = DocsShellCommandsImport.update({
  id: '/shell/commands',
  path: '/shell/commands',
  getParentRoute: () => DocsRoute,
} as any)

const DocsShellActivityMonitorRoute = DocsShellActivityMonitorImport.update({
  id: '/shell/activity-monitor',
  path: '/shell/activity-monitor',
  getParentRoute: () => DocsRoute,
} as any)

const DocsLanguageVectorsRoute = DocsLanguageVectorsImport.update({
  id: '/language/vectors',
  path: '/language/vectors',
  getParentRoute: () => DocsRoute,
} as any)

const DocsLanguageStringsRoute = DocsLanguageStringsImport.update({
  id: '/language/strings',
  path: '/language/strings',
  getParentRoute: () => DocsRoute,
} as any)

const DocsLanguagePatternMatchingRoute =
  DocsLanguagePatternMatchingImport.update({
    id: '/language/pattern-matching',
    path: '/language/pattern-matching',
    getParentRoute: () => DocsRoute,
  } as any)

const DocsLanguageObjectOrientedRoute = DocsLanguageObjectOrientedImport.update(
  {
    id: '/language/object-oriented',
    path: '/language/object-oriented',
    getParentRoute: () => DocsRoute,
  } as any,
)

const DocsLanguageNumbersRoute = DocsLanguageNumbersImport.update({
  id: '/language/numbers',
  path: '/language/numbers',
  getParentRoute: () => DocsRoute,
} as any)

const DocsLanguageGettingStartedRoute = DocsLanguageGettingStartedImport.update(
  {
    id: '/language/getting-started',
    path: '/language/getting-started',
    getParentRoute: () => DocsRoute,
  } as any,
)

const DocsLanguageFunctionsRoute = DocsLanguageFunctionsImport.update({
  id: '/language/functions',
  path: '/language/functions',
  getParentRoute: () => DocsRoute,
} as any)

const DocsLanguageDatesRoute = DocsLanguageDatesImport.update({
  id: '/language/dates',
  path: '/language/dates',
  getParentRoute: () => DocsRoute,
} as any)

const DocsLanguageDataTypesRoute = DocsLanguageDataTypesImport.update({
  id: '/language/data-types',
  path: '/language/data-types',
  getParentRoute: () => DocsRoute,
} as any)

const DocsLanguageControlFlowRoute = DocsLanguageControlFlowImport.update({
  id: '/language/control-flow',
  path: '/language/control-flow',
  getParentRoute: () => DocsRoute,
} as any)

const DocsLanguageBasicSyntaxRoute = DocsLanguageBasicSyntaxImport.update({
  id: '/language/basic-syntax',
  path: '/language/basic-syntax',
  getParentRoute: () => DocsRoute,
} as any)

const DocsLanguageRouteComponentRoute = DocsLanguageRouteComponentImport.update(
  {
    id: '/language/RouteComponent',
    path: '/language/RouteComponent',
    getParentRoute: () => DocsRoute,
  } as any,
)

const DocsGettingStartedInstallationRoute =
  DocsGettingStartedInstallationImport.update({
    id: '/getting-started/installation',
    path: '/getting-started/installation',
    getParentRoute: () => DocsRoute,
  } as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/docs': {
      id: '/docs'
      path: '/docs'
      fullPath: '/docs'
      preLoaderRoute: typeof DocsImport
      parentRoute: typeof rootRoute
    }
    '/docs/': {
      id: '/docs/'
      path: '/'
      fullPath: '/docs/'
      preLoaderRoute: typeof DocsIndexImport
      parentRoute: typeof DocsImport
    }
    '/docs/getting-started/installation': {
      id: '/docs/getting-started/installation'
      path: '/getting-started/installation'
      fullPath: '/docs/getting-started/installation'
      preLoaderRoute: typeof DocsGettingStartedInstallationImport
      parentRoute: typeof DocsImport
    }
    '/docs/language/RouteComponent': {
      id: '/docs/language/RouteComponent'
      path: '/language/RouteComponent'
      fullPath: '/docs/language/RouteComponent'
      preLoaderRoute: typeof DocsLanguageRouteComponentImport
      parentRoute: typeof DocsImport
    }
    '/docs/language/basic-syntax': {
      id: '/docs/language/basic-syntax'
      path: '/language/basic-syntax'
      fullPath: '/docs/language/basic-syntax'
      preLoaderRoute: typeof DocsLanguageBasicSyntaxImport
      parentRoute: typeof DocsImport
    }
    '/docs/language/control-flow': {
      id: '/docs/language/control-flow'
      path: '/language/control-flow'
      fullPath: '/docs/language/control-flow'
      preLoaderRoute: typeof DocsLanguageControlFlowImport
      parentRoute: typeof DocsImport
    }
    '/docs/language/data-types': {
      id: '/docs/language/data-types'
      path: '/language/data-types'
      fullPath: '/docs/language/data-types'
      preLoaderRoute: typeof DocsLanguageDataTypesImport
      parentRoute: typeof DocsImport
    }
    '/docs/language/dates': {
      id: '/docs/language/dates'
      path: '/language/dates'
      fullPath: '/docs/language/dates'
      preLoaderRoute: typeof DocsLanguageDatesImport
      parentRoute: typeof DocsImport
    }
    '/docs/language/functions': {
      id: '/docs/language/functions'
      path: '/language/functions'
      fullPath: '/docs/language/functions'
      preLoaderRoute: typeof DocsLanguageFunctionsImport
      parentRoute: typeof DocsImport
    }
    '/docs/language/getting-started': {
      id: '/docs/language/getting-started'
      path: '/language/getting-started'
      fullPath: '/docs/language/getting-started'
      preLoaderRoute: typeof DocsLanguageGettingStartedImport
      parentRoute: typeof DocsImport
    }
    '/docs/language/numbers': {
      id: '/docs/language/numbers'
      path: '/language/numbers'
      fullPath: '/docs/language/numbers'
      preLoaderRoute: typeof DocsLanguageNumbersImport
      parentRoute: typeof DocsImport
    }
    '/docs/language/object-oriented': {
      id: '/docs/language/object-oriented'
      path: '/language/object-oriented'
      fullPath: '/docs/language/object-oriented'
      preLoaderRoute: typeof DocsLanguageObjectOrientedImport
      parentRoute: typeof DocsImport
    }
    '/docs/language/pattern-matching': {
      id: '/docs/language/pattern-matching'
      path: '/language/pattern-matching'
      fullPath: '/docs/language/pattern-matching'
      preLoaderRoute: typeof DocsLanguagePatternMatchingImport
      parentRoute: typeof DocsImport
    }
    '/docs/language/strings': {
      id: '/docs/language/strings'
      path: '/language/strings'
      fullPath: '/docs/language/strings'
      preLoaderRoute: typeof DocsLanguageStringsImport
      parentRoute: typeof DocsImport
    }
    '/docs/language/vectors': {
      id: '/docs/language/vectors'
      path: '/language/vectors'
      fullPath: '/docs/language/vectors'
      preLoaderRoute: typeof DocsLanguageVectorsImport
      parentRoute: typeof DocsImport
    }
    '/docs/shell/activity-monitor': {
      id: '/docs/shell/activity-monitor'
      path: '/shell/activity-monitor'
      fullPath: '/docs/shell/activity-monitor'
      preLoaderRoute: typeof DocsShellActivityMonitorImport
      parentRoute: typeof DocsImport
    }
    '/docs/shell/commands': {
      id: '/docs/shell/commands'
      path: '/shell/commands'
      fullPath: '/docs/shell/commands'
      preLoaderRoute: typeof DocsShellCommandsImport
      parentRoute: typeof DocsImport
    }
    '/docs/shell/completion-and-editing': {
      id: '/docs/shell/completion-and-editing'
      path: '/shell/completion-and-editing'
      fullPath: '/docs/shell/completion-and-editing'
      preLoaderRoute: typeof DocsShellCompletionAndEditingImport
      parentRoute: typeof DocsImport
    }
    '/docs/shell/customization': {
      id: '/docs/shell/customization'
      path: '/shell/customization'
      fullPath: '/docs/shell/customization'
      preLoaderRoute: typeof DocsShellCustomizationImport
      parentRoute: typeof DocsImport
    }
    '/docs/shell/overview': {
      id: '/docs/shell/overview'
      path: '/shell/overview'
      fullPath: '/docs/shell/overview'
      preLoaderRoute: typeof DocsShellOverviewImport
      parentRoute: typeof DocsImport
    }
    '/docs/shell/pipes-and-redirection': {
      id: '/docs/shell/pipes-and-redirection'
      path: '/shell/pipes-and-redirection'
      fullPath: '/docs/shell/pipes-and-redirection'
      preLoaderRoute: typeof DocsShellPipesAndRedirectionImport
      parentRoute: typeof DocsImport
    }
  }
}

// Create and export the route tree

interface DocsRouteChildren {
  DocsIndexRoute: typeof DocsIndexRoute
  DocsGettingStartedInstallationRoute: typeof DocsGettingStartedInstallationRoute
  DocsLanguageRouteComponentRoute: typeof DocsLanguageRouteComponentRoute
  DocsLanguageBasicSyntaxRoute: typeof DocsLanguageBasicSyntaxRoute
  DocsLanguageControlFlowRoute: typeof DocsLanguageControlFlowRoute
  DocsLanguageDataTypesRoute: typeof DocsLanguageDataTypesRoute
  DocsLanguageDatesRoute: typeof DocsLanguageDatesRoute
  DocsLanguageFunctionsRoute: typeof DocsLanguageFunctionsRoute
  DocsLanguageGettingStartedRoute: typeof DocsLanguageGettingStartedRoute
  DocsLanguageNumbersRoute: typeof DocsLanguageNumbersRoute
  DocsLanguageObjectOrientedRoute: typeof DocsLanguageObjectOrientedRoute
  DocsLanguagePatternMatchingRoute: typeof DocsLanguagePatternMatchingRoute
  DocsLanguageStringsRoute: typeof DocsLanguageStringsRoute
  DocsLanguageVectorsRoute: typeof DocsLanguageVectorsRoute
  DocsShellActivityMonitorRoute: typeof DocsShellActivityMonitorRoute
  DocsShellCommandsRoute: typeof DocsShellCommandsRoute
  DocsShellCompletionAndEditingRoute: typeof DocsShellCompletionAndEditingRoute
  DocsShellCustomizationRoute: typeof DocsShellCustomizationRoute
  DocsShellOverviewRoute: typeof DocsShellOverviewRoute
  DocsShellPipesAndRedirectionRoute: typeof DocsShellPipesAndRedirectionRoute
}

const DocsRouteChildren: DocsRouteChildren = {
  DocsIndexRoute: DocsIndexRoute,
  DocsGettingStartedInstallationRoute: DocsGettingStartedInstallationRoute,
  DocsLanguageRouteComponentRoute: DocsLanguageRouteComponentRoute,
  DocsLanguageBasicSyntaxRoute: DocsLanguageBasicSyntaxRoute,
  DocsLanguageControlFlowRoute: DocsLanguageControlFlowRoute,
  DocsLanguageDataTypesRoute: DocsLanguageDataTypesRoute,
  DocsLanguageDatesRoute: DocsLanguageDatesRoute,
  DocsLanguageFunctionsRoute: DocsLanguageFunctionsRoute,
  DocsLanguageGettingStartedRoute: DocsLanguageGettingStartedRoute,
  DocsLanguageNumbersRoute: DocsLanguageNumbersRoute,
  DocsLanguageObjectOrientedRoute: DocsLanguageObjectOrientedRoute,
  DocsLanguagePatternMatchingRoute: DocsLanguagePatternMatchingRoute,
  DocsLanguageStringsRoute: DocsLanguageStringsRoute,
  DocsLanguageVectorsRoute: DocsLanguageVectorsRoute,
  DocsShellActivityMonitorRoute: DocsShellActivityMonitorRoute,
  DocsShellCommandsRoute: DocsShellCommandsRoute,
  DocsShellCompletionAndEditingRoute: DocsShellCompletionAndEditingRoute,
  DocsShellCustomizationRoute: DocsShellCustomizationRoute,
  DocsShellOverviewRoute: DocsShellOverviewRoute,
  DocsShellPipesAndRedirectionRoute: DocsShellPipesAndRedirectionRoute,
}

const DocsRouteWithChildren = DocsRoute._addFileChildren(DocsRouteChildren)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/docs': typeof DocsRouteWithChildren
  '/docs/': typeof DocsIndexRoute
  '/docs/getting-started/installation': typeof DocsGettingStartedInstallationRoute
  '/docs/language/RouteComponent': typeof DocsLanguageRouteComponentRoute
  '/docs/language/basic-syntax': typeof DocsLanguageBasicSyntaxRoute
  '/docs/language/control-flow': typeof DocsLanguageControlFlowRoute
  '/docs/language/data-types': typeof DocsLanguageDataTypesRoute
  '/docs/language/dates': typeof DocsLanguageDatesRoute
  '/docs/language/functions': typeof DocsLanguageFunctionsRoute
  '/docs/language/getting-started': typeof DocsLanguageGettingStartedRoute
  '/docs/language/numbers': typeof DocsLanguageNumbersRoute
  '/docs/language/object-oriented': typeof DocsLanguageObjectOrientedRoute
  '/docs/language/pattern-matching': typeof DocsLanguagePatternMatchingRoute
  '/docs/language/strings': typeof DocsLanguageStringsRoute
  '/docs/language/vectors': typeof DocsLanguageVectorsRoute
  '/docs/shell/activity-monitor': typeof DocsShellActivityMonitorRoute
  '/docs/shell/commands': typeof DocsShellCommandsRoute
  '/docs/shell/completion-and-editing': typeof DocsShellCompletionAndEditingRoute
  '/docs/shell/customization': typeof DocsShellCustomizationRoute
  '/docs/shell/overview': typeof DocsShellOverviewRoute
  '/docs/shell/pipes-and-redirection': typeof DocsShellPipesAndRedirectionRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/docs': typeof DocsIndexRoute
  '/docs/getting-started/installation': typeof DocsGettingStartedInstallationRoute
  '/docs/language/RouteComponent': typeof DocsLanguageRouteComponentRoute
  '/docs/language/basic-syntax': typeof DocsLanguageBasicSyntaxRoute
  '/docs/language/control-flow': typeof DocsLanguageControlFlowRoute
  '/docs/language/data-types': typeof DocsLanguageDataTypesRoute
  '/docs/language/dates': typeof DocsLanguageDatesRoute
  '/docs/language/functions': typeof DocsLanguageFunctionsRoute
  '/docs/language/getting-started': typeof DocsLanguageGettingStartedRoute
  '/docs/language/numbers': typeof DocsLanguageNumbersRoute
  '/docs/language/object-oriented': typeof DocsLanguageObjectOrientedRoute
  '/docs/language/pattern-matching': typeof DocsLanguagePatternMatchingRoute
  '/docs/language/strings': typeof DocsLanguageStringsRoute
  '/docs/language/vectors': typeof DocsLanguageVectorsRoute
  '/docs/shell/activity-monitor': typeof DocsShellActivityMonitorRoute
  '/docs/shell/commands': typeof DocsShellCommandsRoute
  '/docs/shell/completion-and-editing': typeof DocsShellCompletionAndEditingRoute
  '/docs/shell/customization': typeof DocsShellCustomizationRoute
  '/docs/shell/overview': typeof DocsShellOverviewRoute
  '/docs/shell/pipes-and-redirection': typeof DocsShellPipesAndRedirectionRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/docs': typeof DocsRouteWithChildren
  '/docs/': typeof DocsIndexRoute
  '/docs/getting-started/installation': typeof DocsGettingStartedInstallationRoute
  '/docs/language/RouteComponent': typeof DocsLanguageRouteComponentRoute
  '/docs/language/basic-syntax': typeof DocsLanguageBasicSyntaxRoute
  '/docs/language/control-flow': typeof DocsLanguageControlFlowRoute
  '/docs/language/data-types': typeof DocsLanguageDataTypesRoute
  '/docs/language/dates': typeof DocsLanguageDatesRoute
  '/docs/language/functions': typeof DocsLanguageFunctionsRoute
  '/docs/language/getting-started': typeof DocsLanguageGettingStartedRoute
  '/docs/language/numbers': typeof DocsLanguageNumbersRoute
  '/docs/language/object-oriented': typeof DocsLanguageObjectOrientedRoute
  '/docs/language/pattern-matching': typeof DocsLanguagePatternMatchingRoute
  '/docs/language/strings': typeof DocsLanguageStringsRoute
  '/docs/language/vectors': typeof DocsLanguageVectorsRoute
  '/docs/shell/activity-monitor': typeof DocsShellActivityMonitorRoute
  '/docs/shell/commands': typeof DocsShellCommandsRoute
  '/docs/shell/completion-and-editing': typeof DocsShellCompletionAndEditingRoute
  '/docs/shell/customization': typeof DocsShellCustomizationRoute
  '/docs/shell/overview': typeof DocsShellOverviewRoute
  '/docs/shell/pipes-and-redirection': typeof DocsShellPipesAndRedirectionRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/docs'
    | '/docs/'
    | '/docs/getting-started/installation'
    | '/docs/language/RouteComponent'
    | '/docs/language/basic-syntax'
    | '/docs/language/control-flow'
    | '/docs/language/data-types'
    | '/docs/language/dates'
    | '/docs/language/functions'
    | '/docs/language/getting-started'
    | '/docs/language/numbers'
    | '/docs/language/object-oriented'
    | '/docs/language/pattern-matching'
    | '/docs/language/strings'
    | '/docs/language/vectors'
    | '/docs/shell/activity-monitor'
    | '/docs/shell/commands'
    | '/docs/shell/completion-and-editing'
    | '/docs/shell/customization'
    | '/docs/shell/overview'
    | '/docs/shell/pipes-and-redirection'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/docs'
    | '/docs/getting-started/installation'
    | '/docs/language/RouteComponent'
    | '/docs/language/basic-syntax'
    | '/docs/language/control-flow'
    | '/docs/language/data-types'
    | '/docs/language/dates'
    | '/docs/language/functions'
    | '/docs/language/getting-started'
    | '/docs/language/numbers'
    | '/docs/language/object-oriented'
    | '/docs/language/pattern-matching'
    | '/docs/language/strings'
    | '/docs/language/vectors'
    | '/docs/shell/activity-monitor'
    | '/docs/shell/commands'
    | '/docs/shell/completion-and-editing'
    | '/docs/shell/customization'
    | '/docs/shell/overview'
    | '/docs/shell/pipes-and-redirection'
  id:
    | '__root__'
    | '/'
    | '/docs'
    | '/docs/'
    | '/docs/getting-started/installation'
    | '/docs/language/RouteComponent'
    | '/docs/language/basic-syntax'
    | '/docs/language/control-flow'
    | '/docs/language/data-types'
    | '/docs/language/dates'
    | '/docs/language/functions'
    | '/docs/language/getting-started'
    | '/docs/language/numbers'
    | '/docs/language/object-oriented'
    | '/docs/language/pattern-matching'
    | '/docs/language/strings'
    | '/docs/language/vectors'
    | '/docs/shell/activity-monitor'
    | '/docs/shell/commands'
    | '/docs/shell/completion-and-editing'
    | '/docs/shell/customization'
    | '/docs/shell/overview'
    | '/docs/shell/pipes-and-redirection'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DocsRoute: typeof DocsRouteWithChildren
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DocsRoute: DocsRouteWithChildren,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/docs"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/docs": {
      "filePath": "docs.tsx",
      "children": [
        "/docs/",
        "/docs/getting-started/installation",
        "/docs/language/RouteComponent",
        "/docs/language/basic-syntax",
        "/docs/language/control-flow",
        "/docs/language/data-types",
        "/docs/language/dates",
        "/docs/language/functions",
        "/docs/language/getting-started",
        "/docs/language/numbers",
        "/docs/language/object-oriented",
        "/docs/language/pattern-matching",
        "/docs/language/strings",
        "/docs/language/vectors",
        "/docs/shell/activity-monitor",
        "/docs/shell/commands",
        "/docs/shell/completion-and-editing",
        "/docs/shell/customization",
        "/docs/shell/overview",
        "/docs/shell/pipes-and-redirection"
      ]
    },
    "/docs/": {
      "filePath": "docs/index.tsx",
      "parent": "/docs"
    },
    "/docs/getting-started/installation": {
      "filePath": "docs/getting-started/installation.tsx",
      "parent": "/docs"
    },
    "/docs/language/RouteComponent": {
      "filePath": "docs/language/RouteComponent.tsx",
      "parent": "/docs"
    },
    "/docs/language/basic-syntax": {
      "filePath": "docs/language/basic-syntax.tsx",
      "parent": "/docs"
    },
    "/docs/language/control-flow": {
      "filePath": "docs/language/control-flow.tsx",
      "parent": "/docs"
    },
    "/docs/language/data-types": {
      "filePath": "docs/language/data-types.tsx",
      "parent": "/docs"
    },
    "/docs/language/dates": {
      "filePath": "docs/language/dates.tsx",
      "parent": "/docs"
    },
    "/docs/language/functions": {
      "filePath": "docs/language/functions.tsx",
      "parent": "/docs"
    },
    "/docs/language/getting-started": {
      "filePath": "docs/language/getting-started.tsx",
      "parent": "/docs"
    },
    "/docs/language/numbers": {
      "filePath": "docs/language/numbers.tsx",
      "parent": "/docs"
    },
    "/docs/language/object-oriented": {
      "filePath": "docs/language/object-oriented.tsx",
      "parent": "/docs"
    },
    "/docs/language/pattern-matching": {
      "filePath": "docs/language/pattern-matching.tsx",
      "parent": "/docs"
    },
    "/docs/language/strings": {
      "filePath": "docs/language/strings.tsx",
      "parent": "/docs"
    },
    "/docs/language/vectors": {
      "filePath": "docs/language/vectors.tsx",
      "parent": "/docs"
    },
    "/docs/shell/activity-monitor": {
      "filePath": "docs/shell/activity-monitor.tsx",
      "parent": "/docs"
    },
    "/docs/shell/commands": {
      "filePath": "docs/shell/commands.tsx",
      "parent": "/docs"
    },
    "/docs/shell/completion-and-editing": {
      "filePath": "docs/shell/completion-and-editing.tsx",
      "parent": "/docs"
    },
    "/docs/shell/customization": {
      "filePath": "docs/shell/customization.tsx",
      "parent": "/docs"
    },
    "/docs/shell/overview": {
      "filePath": "docs/shell/overview.tsx",
      "parent": "/docs"
    },
    "/docs/shell/pipes-and-redirection": {
      "filePath": "docs/shell/pipes-and-redirection.tsx",
      "parent": "/docs"
    }
  }
}
ROUTE_MANIFEST_END */
